# Reference this view as main__products
schema: main
table_name: products

dimensions:
  cost: {}
  category: {}
  name: {}
  brand: {}
  retail_price: {}
  department: {}
  sku: {}

  id:
    format: ID
    primary_key: true

  distribution_center_id:
    format: ID

measures:
  count:
    aggregate_type: count
