# Reference this view as prod_marts__mart_category_performance
measures:
  cost_sum:
    sql: ${prod_marts__mart_category_performance.cost}
    aggregate_type: sum

  orders_count_distinct:
    sql: ${prod_marts__mart_category_performance.orders}
    aggregate_type: count_distinct
